# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adventure_description', models.TextField(max_length=256)),
                ('before_adventure', models.TextField(max_length=256)),
                ('avoid_next_time', models.TextField(max_length=256)),
                ('recommend_next_time', models.TextField(max_length=256)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Location')),
            ],
        ),
    ]
