# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funny_facts', models.TextField(max_length=256)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Country')),
            ],
        ),
    ]
